language: node_js
node_js:
  - node
install:
  - npm install
script:
  - npm run lint
  - npm run build
deploy:
  - provider: pages
    skip-cleanup: true

    # OAuth token, generated at https://github.com/settings/tokens,
    # set in travis-ci dashboard, marked secure (Disable displaying value in log)
    github-token: $GITHUB_TOKEN

    keep-history: true
    on:
      branch: master
      condition: $GITHUB_TOKEN != ""